### ISSUE TITLE
Desktop: "WORK" and "LOGIN" buttons are too much towards right.hence work button touching the right border

### ISSUE THREAD

**Issue by rashmi73** [topcoder-platform/community-nav-prototype#26]
**Describe the bug**
On desktop, "WORK" and "LOGIN" buttons are too much towards right.hence work button touching the right border

**To Reproduce**
1. Go to 'http://localhost:3000/dark' or 'http://localhost:3000/light'
2. Observe on top right buttons

**Expected behavior**
should be centered mostly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: all desktop web browsers
 - Version: [e.g. 22]

**Devices:**
- Desktop

**Additional context**

**Comment by rashmi73** [comment]
@ThomasKranitsas sorry it is already solved

**Comment by ThomasKranitsas** [comment]
@rashmi73 can you please upload a screenshot?

**Comment by ThomasKranitsas** [comment]
ah, ok
