### ISSUE TITLE
Clicking on left upper topcoder logo should referesh the page to the start

### ISSUE THREAD

**Issue by rashmi73** [topcoder-platform/community-nav-prototype#27]
**Describe the bug**
Clicking on left upper topcoder logo should referesh the page to the start

**To Reproduce**
1. Go to 'http://localhost:3000/light' or 'http://localhost:3000/light'
2. Click on 'left upper logo'
3. Nothing happens

**Expected behavior**
Should select "BUSINESS" tab

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: all desktop web browsers

**Devices:**
- Desktop

**Additional context**

**Comment by ThomasKranitsas** [comment]
This will be handled in #2
