### ISSUE TITLE
Submenu more item margin/padding left are different from other submenu items

### ISSUE THREAD

**Issue by iversonLv** [topcoder-platform/community-nav-prototype#47]
Don't know whether is the purpose or not as I check the CSS it's set !important for more item margin left.

Maybe because it's more item not a NORMAL submenu, so less margin for it.

Anyway, log here, if it's purpose just directly close the ticket.

![image](https://user-images.githubusercontent.com/4952611/56098554-034fa480-5f34-11e9-98b3-e739461a0dc2.png)

Thanks.

**Comment by iversonLv** [comment]
At smaller viewport, it's 10px v.s. others 20px

**Comment by iversonLv** [comment]
Associated issue:
Submenu more button padding are different
Triple menu more button has an equal left/right padding
But the secondary menu more button has 0 left padding

Secondary menu
![image](https://user-images.githubusercontent.com/4952611/56098745-29764400-5f36-11e9-9958-8b7fdced1cac.png)

Triple menu
![image](https://user-images.githubusercontent.com/4952611/56098741-1b282800-5f36-11e9-986d-0cad68463603.png)

**Comment by ThomasKranitsas** [comment]
closing this one. Will track the issue in #52
