### ISSUE TITLE
Notifications component should have fixed height and the content should be scrollable

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-nav-prototype#62]
**Describe the bug**
The notifications component should have a fixed height similar to when there are no notifications and the content should be scrollable

**To Reproduce**
1. Go to https://tc-unified-nav.herokuapp.com/light
2. Click on the notifications icon
3. See error

**Expected behavior**
The height should be fixed

**Screenshots**
<img width="1377" alt="Screenshot 2019-04-29 at 20 32 32" src="https://user-images.githubusercontent.com/4612921/56914894-ef707a80-6abd-11e9-9e44-e906eedef298.png">

**Devices:**
- Desktop
- Tablet

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors this is open for pickup.

We will not use `tcx_` labels (except the `tcx_ReadyForReview` as there's currently an issue with Topcoder-X.

I'll be processing payments manually.

Prize: $20
PR on `develop`

**Comment by gurmeetb** [comment]
@marioskranitsas looks like we clicked together assign myself, feel free to take it back.

**Comment by ThomasKranitsas** [comment]
What a timing! 😃 You guys literally clicked on the exact same second.

**Comment by gurmeetb** [comment]
@ThomasKranitsas looks like just a gap of 1-2 secs 😜
