### ISSUE TITLE
Make the notification section headers sticky

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-nav-prototype#64]
**Describe the feature**
We need the section headers of the notification component to be sticky like they are on the mobile.

**Devices:**
- Desktop
- Tablet

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/processors this is open for pickup.

We will not use `tcx_` labels (except the `tcx_ReadyForReview` as there's currently an issue with Topcoder-X.

I'll be processing payments manually.

Prize: $40
PR on `develop`

**Comment by ThomasKranitsas** [comment]
seems like @applehit16 got it first

**Comment by ThomasKranitsas** [comment]
thanks @rashmi73

**Comment by rashmi73** [comment]
@ThomasKranitsas yes 12 seconds earlier

**Comment by ThomasKranitsas** [comment]
I'll be opening more tickets but feel free to open tickets for the notification component if you want and I'll open them for pickup

**Comment by applehit16** [comment]
@ThomasKranitsas just want to mention that the mobile version is actually not working either, it just fakes the first header to be sticky
![Apr-29-2019 18-50-43](https://user-images.githubusercontent.com/48845164/56937115-df519e80-6aaf-11e9-9182-f2801e8fadea.gif)

The notification is clickable on if you turn chrome devtool to be in mobile mode. But it seems not clickable in mobile. I'm using iphone6+, not working in both safari and chrome mobile

**Comment by applehit16** [comment]
I was looking for position detection code, but couldn't find it and then realized the first sticky is hard-coded 😂

**Comment by ThomasKranitsas** [comment]
Can you please fix the mobile as well? I'll bump up the payment

**Comment by liqiang372** [comment]
@ThomasKranitsas will do, I probably need more time

**Comment by applehit16** [comment]
@ThomasKranitsas will do, I probably need more time

**Comment by ThomasKranitsas** [comment]
Ok, please make sure you are only using one of your accounts 😉 Not everyone is aware of your situation and ppl may get confused.

Thanks!
