### ISSUE TITLE
Notification header on mobile does not match the spec

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-nav-prototype#70]
**Expected behavior**
Should match the spec

**Screenshots**
![Image 2019-04-24 11-28-41](https://user-images.githubusercontent.com/4612921/56948582-394a7680-6b39-11e9-9d75-c7e201c7b584.png)

**Devices:**
- Mobile

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors this is open for pickup

Prize: $20
PR on `develop`

**Comment by ThomasKranitsas** [comment]
2sec difference 😛

**Comment by nahidshahin** [comment]
How do you guys compete on second level? Do you have any bot written?  Before even get email notification of "open for pickup".

**Comment by ThomasKranitsas** [comment]
@nahidshahin you can `watch` the repo and receive an email right when I open new tickets 😉You can then just wait for me to open it for pickup.

**Comment by nahidshahin** [comment]
@ThomasKranitsas that's what exactly I'm doing 😉 But people are too fast

**Comment by ThomasKranitsas** [comment]
Yeah, I'm very surprised and happy at the same time! More tickets coming soon. Stay tuned!

**Comment by nahidshahin** [comment]
@ThomasKranitsas  Just one request, please open good amount of issues at once.
