### ISSUE TITLE
Notification dismiss tooltip is not showing properly

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-nav-prototype#71]
**Describe the bug**
Because of the `overflow: scroll` property, the notification dismiss (x) tooltip is not showing up properly.

**Screenshots**
<img width="1332" alt="Screenshot 2019-04-30 at 11 18 37" src="https://user-images.githubusercontent.com/4612921/56948772-d5747d80-6b39-11e9-8f1f-1796312c74a6.png">

**Devices:**
- Desktop
- Tablet

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors this is open for pickup

Prize: $20
PR on `develop`

**Comment by sumitdaga** [comment]
not this time :)

**Comment by ThomasKranitsas** [comment]
That was fast! 🚀

**Comment by sumitdaga** [comment]
`overflow-x: visible;`
`overflow-y: auto/scroll;`

will not work https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue/6433475#6433475

**Comment by ThomasKranitsas** [comment]
what do you suggest?

**Comment by sumitdaga** [comment]
if i am not wrong, the only simple solution is to move the tooltip to the left :)

**Comment by ThomasKranitsas** [comment]
Ok, let's push the tooltip a bit to the left.
