### ISSUE TITLE
Notification card size is not correct

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-nav-prototype#73]
**Describe the bug**
There seems to be more padding than needed.

**Expected behavior**
 
![Image 2019-04-24 11-34-42](https://user-images.githubusercontent.com/4612921/56949571-f5a53c00-6b3b-11e9-8d86-fa1767d3b659.png)

**Screenshots**
![Image 2019-04-24 11-35-08](https://user-images.githubusercontent.com/4612921/56949573-f8a02c80-6b3b-11e9-99a3-c187101a576d.png)

**Devices:**
- Desktop
- Tablet

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors open for pickup

Prize: $20
PR on `develop`

**Comment by applehit16** [comment]
Ha, I guess using mobile doesn’t even stand a chance to win

**Comment by nahidshahin** [comment]
PR https://github.com/topcoder-platform/community-nav-prototype/pull/75
