### ISSUE TITLE
A scrollbar is outside the scrolling container

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-nav-prototype#78]
A scrollbar is outside the scrolling container

![Topcoder 2019-04-30 18-09-54](https://user-images.githubusercontent.com/683231/56962315-dcb87d00-6b73-11e9-935d-09dd174d925d.png)

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors open for pickup 

Prize: $40
PR on `develop`

Requirement:
- The header should be fixed at the top and only the content should be scrollable with sticky section headers.
